GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2

  | Name                 | Type                    | Params
-----------------------------------------------------------------
0 | _type_loss           | BCELoss                 | 0     
1 | _order_loss          | CrossEntropyLoss        | 0     
2 | _audio_feature_model | AudioFeatureModel       | 964 K 
3 | _input_projection    | Sequential              | 66 K  
4 | _encoder_layer       | TransformerEncoderLayer | 99 K  
5 | _encoder             | TransformerEncoder      | 398 K 
6 | _type_mlp            | Sequential              | 17 K  
7 | _order_mlp           | Sequential              | 17 K  
8 | _contrastive_mlp     | Sequential              | 33 K  
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/sgurram/Projects/temporal_contrastive_learning/train.py", line 47, in <module>
    trainer.fit(model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 282, in ddp_train
    results = self.train_or_test()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 466, in train
    self.run_sanity_check(self.get_model())
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 658, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 566, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sgurram/Projects/temporal_contrastive_learning/data.py", line 103, in __getitem__
    anchor, spatial = get_augmented_views(filePath)
  File "/home/sgurram/Projects/temporal_contrastive_learning/augment.py", line 96, in get_augmented_views
    return augment(sample, wave1, spec1, threshold1), augment(sample, wave2, spec2, threshold2)
  File "/home/sgurram/Projects/temporal_contrastive_learning/augment.py", line 66, in augment
    spec = spec_transform(threshold)(SpecFixedCrop(threshold)(spec))
  File "/home/sgurram/Projects/temporal_contrastive_learning/transforms.py", line 186, in __call__
    return f(t(spec))
  File "/home/sgurram/Projects/temporal_contrastive_learning/transforms.py", line 175, in __call__
    return torchaudio.transforms.FrequencyMasking(size)(specgram=spec)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torchaudio/transforms.py", line 818, in forward
    return F.mask_along_axis(specgram, self.mask_param, mask_value, self.axis)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torchaudio/functional.py", line 1568, in mask_along_axis
    assert mask_end - mask_start < mask_param
AssertionError

Traceback (most recent call last):
  File "/home/sgurram/Projects/temporal_contrastive_learning/train.py", line 47, in <module>
    trainer.fit(model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 282, in ddp_train
    results = self.train_or_test()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 466, in train
    self.run_sanity_check(self.get_model())
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 658, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 566, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sgurram/Projects/temporal_contrastive_learning/data.py", line 103, in __getitem__
    anchor, spatial = get_augmented_views(filePath)
  File "/home/sgurram/Projects/temporal_contrastive_learning/augment.py", line 75, in get_augmented_views
    sample, _ = get_wave(path)
  File "/home/sgurram/Projects/temporal_contrastive_learning/augment.py", line 25, in get_wave
    wave, samp_freq = torchaudio.load(path)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torchaudio/backend/sox_io_backend.py", line 105, in load
    filepath, frame_offset, num_frames, normalize, channels_first)
RuntimeError: Error reading audio file: unkown length.

